/*
 * Host API
 *
 * API for posting hosts and waiting for hosts
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the MIT License
 */

package swagger

type DefaultMessages struct {
	Game Game `json:"game,omitempty"`

	// Default message when hosting a game.
	DefaultHost string `json:"default_host,omitempty"`

	// Default message when waiting for someone else to host a game.
	DefaultWait string `json:"default_wait,omitempty"`

	// String to use instead of 'is hosting' when showing in hosting lists.
	IsHosting string `json:"is_hosting,omitempty"`

	// String to use instead of 'playing vs' when showing in hosting lists.
	IsPlaying string `json:"is_playing,omitempty"`
}
