/*
 * Host API
 *
 * API for posting hosts and waiting for hosts
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the MIT License
 */

package swagger

import (
	"time"
)

type Identity struct {

	// Latitude component of the location
	PlayerID   uint64    `json:"player_id,omitempty"`
	Credential string    `json:"credential,omitempty"`
	Created    time.Time `json:"date,omitempty"`
	Nick       string    `json:"nick,omitempty"`
	AuthRealm  Realm     `json:"location,omitempty"`
	// Longitutde component of the location
	AuthTypes []string `json:"auth,omitempty"`
}
