/*
 * Host API
 *
 * API for posting hosts and waiting for hosts
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the MIT License
 */

package swagger

type Location struct {

	// Latitude component of the location
	Lat float64 `json:"lat,omitempty"`

	// Longitutde component of the location
	Long float64 `json:"long,omitempty"`
}
