/*
 * Host API
 *
 * API for posting hosts and waiting for hosts
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the MIT License
 */

package swagger

type Realm struct {

	// Latitude component of the location
	ID   uint16 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	// Longitutde component of the location
	AuthTypes []string `json:"auth,omitempty"`
}
