/*
 * Host API
 *
 * API for posting hosts and waiting for hosts
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the MIT License
 */

package swagger

import (
	"time"
)

type User struct {

	// Unique identifier for the user
	Id uint64 `json:"id,omitempty"`

	// Nickname for the user
	Nick string `json:"nick,omitempty"`

	Location Location `json:"location,omitempty"`

	// The most recently seen IPv4 for the user
	Ipv4 string `json:"ipv4,omitempty"`

	// The most recently seen IPv6 for the user
	Ipv6 string `json:"ipv6,omitempty"`

	// Static IP?
	StaticIP bool `json:"static_ip,omitempty"`

	// Priv level e.g. user/admin/super
	PrivLevel string `json:"privs,omitempty"`

	// User's preferred port to host on
	Port int `json:"preferred_port,omitempty"`

	// Preferred Gender for the user
	Gender string `json:"gender,omitempty"`

	// Whether the user will be named in host lists as an opponent
	Private bool `json:"private,omitempty"`

	// Want Join Notification ?
	JoinNotify bool `json:"join_notification,omitempty"`

	// Password for the user.
	HasPassword bool `json:"password_set,omitempty"`

	// Creation time for the user record.
	Created time.Time `json:"created,omitempty"`

	// Email address of the user.
	Email string `json:"email,omitempty"`

	// Avatar URL of the user.
	Picture string `json:"picture,omitempty"`

	// Known Identities for the user
	Credentials []*Identity `json:"identities,omitempty"`

	// Challonge Information
	ChallongeInfo []*ChallongeDetails `json:"challonge,omitempty"`

	DefaultMessages []DefaultMessages `json:"default_messages,omitempty"`
}
