/*
 * Host API
 *
 * API for posting hosts and waiting for hosts
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the MIT License
 */

package swagger

type UserHistory struct {

	// Position in pagination.
	Offset int32 `json:"offset,omitempty"`

	// Number of items to retrieve (100 max).
	Limit int32 `json:"limit,omitempty"`

	// Total number of items available.
	Count int32 `json:"count,omitempty"`

	Hosts HostList `json:"hosts,omitempty"`
}
