/*
 * Host API
 *
 * API for posting hosts and waiting for hosts
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the MIT License
 */

package swagger

import (
	"time"
)

type Waiter struct {

	// Unique identifier for a given waiting host.
	Id uint64 `json:"id,omitempty"`

	User User `json:"user,omitempty"`

	// Hosting/waiting message.
	Message string `json:"message,omitempty"`

	// Name of the person involved.
	DisplayName string `json:"display_name,omitempty"`

	// Who this waiter joined, if known.
	JoinedID int64 `json:"joined_id,omitempty"`

	// Time when the host appeared.
	Started time.Time `json:"wait_until,omitempty"`

	// How long this waiter will advertise until
	WaitUntil time.Time `json:"started,omitempty"`

	// Whether this is a host or somebody waiting.
	IsHosting bool `json:"is_hosting,omitempty"`

	Game Game `json:"game,omitempty"`
}
